/**
 * This file is auto-generated from the Google Spreadsheet package.
 * It contains the list of available locales and their mappings to original spreadsheet headers.
 * Do not edit this file manually, it will be overwritten by the package.
 */

 export const locales = ["de"];

/**
 * Mapping from normalized locale codes to original spreadsheet headers
 * Used for syncing changes back to the spreadsheet
 */
export const localeHeaderMapping = {
  "de": "de"
};

export default locales;
